name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

# Grant the token rights to update branches and Pages
permissions:
  contents: write # allow pushing commits
  pages: write # allow updating GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # (you can repeat permissions here if you prefer per-job granularity)
    permissions:
      contents: write
      pages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci
        working-directory: ./react-portfolio

      - name: Build
        run: npm run build
        working-directory: ./react-portfolio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./react-portfolio/build
