name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install dependencies (inside react-portfolio)
      - name: Install dependencies
        working-directory: ./react-portfolio
        run: npm install

      # 4. Build (inside react-portfolio)
      - name: Build
        working-directory: ./react-portfolio
        run: npm run build

      # 5. Deploy the build folder
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react-portfolio/build
